name: Build and Deploy

on:
  push:
    branches:
      - 'main'
      - 'master'
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Docker tags
      - name: Generate Docker tags
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}/costrict-manual
          # 这是修改后的核心部分
          tags: |
            # 1. 只有当推送到默认主分支时，才生成 'latest' 标签
            type=raw,value=latest,enable={{is_default_branch}}

            # 2. 当推送新标签时，使用标签名作为镜像标签 (例如 v1.2.3)
            type=ref,event=tag

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          target: runner
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Deploy to Server
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "Connected to server!"
            cd /home/zhuge/docs
            sudo docker compose pull
            sudo docker compose up -d --force-recreate
            echo "Deployment finished successfully!"